/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject2;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class subMain111 extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    public void playSound() {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("C:\\Users\\HP\\Downloads\\Click2-Sebastian-759472264.wav"));
//            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("C:\\Users\\HP\\Downloads\\Click On-SoundBible.com-1697535117.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();
        }
    }

    public void playSound1() {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("C:\\Users\\HP\\Downloads\\Button-SoundBible.com-1420500901.wav"));

            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();
        }
    }

    /**
     * Creates new form subMain
     */
    public subMain111() {
        initComponents();
        admin.setForeground(new Color(187, 187, 187));
        hospital.setForeground(new Color(187, 187, 187));
        hospital1.setForeground(new Color(187, 187, 187));
        hospital2.setForeground(new Color(187, 187, 187));
        hospital3.setForeground(new Color(187, 187, 187));
        hospital4.setForeground(new Color(187, 187, 187));
        hospital5.setForeground(new Color(187, 187, 187));
        hospital6.setForeground(new Color(187, 187, 187));
        hospital7.setForeground(new Color(187, 187, 187));
        hospital8.setForeground(new Color(187, 187, 187));
        hospital9.setForeground(new Color(187, 187, 187));
        panel_drag2.setForeground(new Color(32, 33, 35));

    }

    class JpanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(165, 71, 160);
            Color color2 = new Color(66, 39, 90);
            GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JpanelGradient();
        jPanel5 = new javax.swing.JPanel();
        hospital = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hotel = new javax.swing.JPanel();
        hospital1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        shoppingMall = new javax.swing.JPanel();
        hospital2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        banks = new javax.swing.JPanel();
        hospital3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        schools = new javax.swing.JPanel();
        hospital4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numbers = new javax.swing.JPanel();
        hospital5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        restaurants = new javax.swing.JPanel();
        hospital6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        colleges = new javax.swing.JPanel();
        hospital7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        university = new javax.swing.JPanel();
        hospital8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        panel_drag2 = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        airport = new javax.swing.JPanel();
        hospital9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(32, 33, 35));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        hospital.setText("HOSPITAL");
        hospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospitalMouseEntered(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\medical_doctor_30px.png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hospital)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hotel.setBackground(new java.awt.Color(32, 33, 35));
        hotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hotelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hotelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hotelMouseExited(evt);
            }
        });

        hospital1.setText("HOTELS");
        hospital1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital1MouseEntered(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\hotel_star_30px.png")); // NOI18N

        javax.swing.GroupLayout hotelLayout = new javax.swing.GroupLayout(hotel);
        hotel.setLayout(hotelLayout);
        hotelLayout.setHorizontalGroup(
            hotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hotelLayout.setVerticalGroup(
            hotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hospital1)
                .addGap(15, 15, 15))
        );

        shoppingMall.setBackground(new java.awt.Color(32, 33, 35));
        shoppingMall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shoppingMall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shoppingMallMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shoppingMallMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shoppingMallMouseExited(evt);
            }
        });

        hospital2.setText("SHOPPING MALLS");
        hospital2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital2MouseEntered(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\shopping_bag_30px.png")); // NOI18N

        javax.swing.GroupLayout shoppingMallLayout = new javax.swing.GroupLayout(shoppingMall);
        shoppingMall.setLayout(shoppingMallLayout);
        shoppingMallLayout.setHorizontalGroup(
            shoppingMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shoppingMallLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital2)
                .addGap(12, 12, 12))
        );
        shoppingMallLayout.setVerticalGroup(
            shoppingMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shoppingMallLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hospital2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        banks.setBackground(new java.awt.Color(32, 33, 35));
        banks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        banks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banksMouseExited(evt);
            }
        });

        hospital3.setText("BANKS");
        hospital3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital3MouseEntered(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\visa_30px.png")); // NOI18N

        javax.swing.GroupLayout banksLayout = new javax.swing.GroupLayout(banks);
        banks.setLayout(banksLayout);
        banksLayout.setHorizontalGroup(
            banksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, banksLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        banksLayout.setVerticalGroup(
            banksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(banksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(banksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospital3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        schools.setBackground(new java.awt.Color(32, 33, 35));
        schools.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        schools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schoolsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                schoolsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                schoolsMouseExited(evt);
            }
        });

        hospital4.setText("SCHOOLS");
        hospital4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital4MouseEntered(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\school_30px.png")); // NOI18N

        javax.swing.GroupLayout schoolsLayout = new javax.swing.GroupLayout(schools);
        schools.setLayout(schoolsLayout);
        schoolsLayout.setHorizontalGroup(
            schoolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, schoolsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hospital4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        schoolsLayout.setVerticalGroup(
            schoolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schoolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(schoolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(schoolsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hospital4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        numbers.setBackground(new java.awt.Color(32, 33, 35));
        numbers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numbers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numbersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numbersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numbersMouseExited(evt);
            }
        });

        hospital5.setText("NUMBERS");
        hospital5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital5MouseEntered(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\phone_30px.png")); // NOI18N

        javax.swing.GroupLayout numbersLayout = new javax.swing.GroupLayout(numbers);
        numbers.setLayout(numbersLayout);
        numbersLayout.setHorizontalGroup(
            numbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numbersLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        numbersLayout.setVerticalGroup(
            numbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numbersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numbersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospital5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        restaurants.setBackground(new java.awt.Color(32, 33, 35));
        restaurants.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restaurants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaurantsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restaurantsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaurantsMouseExited(evt);
            }
        });

        hospital6.setText("RESTAURANTS");
        hospital6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hospital6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital6MouseEntered(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\restaurant_30px.png")); // NOI18N

        javax.swing.GroupLayout restaurantsLayout = new javax.swing.GroupLayout(restaurants);
        restaurants.setLayout(restaurantsLayout);
        restaurantsLayout.setHorizontalGroup(
            restaurantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restaurantsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        restaurantsLayout.setVerticalGroup(
            restaurantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restaurantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospital6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        colleges.setBackground(new java.awt.Color(32, 33, 35));
        colleges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colleges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                collegesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                collegesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                collegesMouseExited(evt);
            }
        });

        hospital7.setText("COLLEGES");
        hospital7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital7MouseEntered(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\student_center_30px.png")); // NOI18N

        javax.swing.GroupLayout collegesLayout = new javax.swing.GroupLayout(colleges);
        colleges.setLayout(collegesLayout);
        collegesLayout.setHorizontalGroup(
            collegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collegesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        collegesLayout.setVerticalGroup(
            collegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collegesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(collegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(collegesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hospital7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        university.setBackground(new java.awt.Color(32, 33, 35));
        university.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        university.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                universityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                universityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                universityMouseExited(evt);
            }
        });

        hospital8.setText("UNIVERSITIES");
        hospital8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hospital8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital8MouseEntered(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\university_30px.png")); // NOI18N

        javax.swing.GroupLayout universityLayout = new javax.swing.GroupLayout(university);
        university.setLayout(universityLayout);
        universityLayout.setHorizontalGroup(
            universityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, universityLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        universityLayout.setVerticalGroup(
            universityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, universityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(universityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hospital8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(32, 33, 35));

        admin.setBackground(new java.awt.Color(187, 187, 187));
        admin.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        admin.setText("Admin Login");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        panel_drag2.setOpaque(false);
        panel_drag2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_drag2MouseDragged(evt);
            }
        });
        panel_drag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_drag2MousePressed(evt);
            }
        });

        btn_close.setBackground(new java.awt.Color(165, 71, 160));
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\JavaApplication11\\src\\menu\\icons8_delete_26px.png")); // NOI18N
        btn_close.setBorder(null);
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setFocusPainted(false);
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\back_to_50px.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_drag2Layout = new javax.swing.GroupLayout(panel_drag2);
        panel_drag2.setLayout(panel_drag2Layout);
        panel_drag2Layout.setHorizontalGroup(
            panel_drag2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_drag2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_drag2Layout.setVerticalGroup(
            panel_drag2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_drag2Layout.createSequentialGroup()
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        airport.setBackground(new java.awt.Color(32, 33, 35));
        airport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        airport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                airportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                airportMouseExited(evt);
            }
        });

        hospital9.setText("AIRPORT");
        hospital9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospital9MouseEntered(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\airport_30px.png")); // NOI18N

        javax.swing.GroupLayout airportLayout = new javax.swing.GroupLayout(airport);
        airport.setLayout(airportLayout);
        airportLayout.setHorizontalGroup(
            airportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, airportLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospital9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        airportLayout.setVerticalGroup(
            airportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(airportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(airportLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hospital9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_drag2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colleges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(airport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shoppingMall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(restaurants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(university, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_drag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shoppingMall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restaurants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colleges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(university, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(airport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_drag2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_drag2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel_drag2MouseDragged

    private void panel_drag2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_drag2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_drag2MousePressed

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        btn_close.setBackground(new Color(66, 39, 90));
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        btn_close.setBackground(new Color(165, 71, 160));
    }//GEN-LAST:event_btn_closeMouseExited

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void hospitalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospitalMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_hospitalMouseEntered

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(52, 53, 55));

//        InputStream in;
//        try {
//            in = new FileInputStream(new File("C:\\Users\\HP\\Downloads\\mixkit-fast-double-click-on-mouse-275.wav"));
//            audioInputStream audios = new 
//        
//        
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        }
        playSound();

    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:        
        jPanel5.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_jPanel5MouseExited

    private void hospital1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hospital1MouseEntered

    private void hotelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotelMouseEntered
        // TODO add your handling code here:

        playSound();
        hotel.setBackground(new Color(52, 53, 55));


    }//GEN-LAST:event_hotelMouseEntered

    private void hotelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotelMouseExited
        // TODO add your handling code here:
        hotel.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_hotelMouseExited

    private void hospital2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hospital2MouseEntered

    private void shoppingMallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoppingMallMouseEntered
        // TODO add your handling code here:    
        playSound();

        shoppingMall.setBackground(new Color(52, 53, 55));


    }//GEN-LAST:event_shoppingMallMouseEntered

    private void shoppingMallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoppingMallMouseExited
        // TODO add your handling code here:
        shoppingMall.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_shoppingMallMouseExited

    private void hospital3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hospital3MouseEntered

    private void banksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banksMouseEntered
        // TODO add your handling code here:
        playSound();

        banks.setBackground(new Color(52, 53, 55));

    }//GEN-LAST:event_banksMouseEntered

    private void banksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banksMouseExited
        // TODO add your handling code here:
        banks.setBackground(new Color(32, 33, 35));


    }//GEN-LAST:event_banksMouseExited

    private void hospital4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital4MouseEntered
        // TODO add your handling code here:
        playSound();

        schools.setBackground(new Color(52, 53, 55));

    }//GEN-LAST:event_hospital4MouseEntered

    private void schoolsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolsMouseEntered
        // TODO add your handling code here:
        playSound();

        schools.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_schoolsMouseEntered

    private void schoolsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolsMouseExited

    private void hospital5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hospital5MouseEntered

    private void numbersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numbersMouseEntered
        // TODO add your handling code here:
        playSound();

        numbers.setBackground(new Color(52, 53, 55));

    }//GEN-LAST:event_numbersMouseEntered

    private void numbersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numbersMouseExited
        // TODO add your handling code here:
        numbers.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_numbersMouseExited

    private void hospital6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hospital6MouseEntered

    private void restaurantsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantsMouseEntered
        // TODO add your handling code here:
        playSound();

        restaurants.setBackground(new Color(52, 53, 55));

    }//GEN-LAST:event_restaurantsMouseEntered

    private void restaurantsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantsMouseExited
        // TODO add your handling code here:
        restaurants.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_restaurantsMouseExited

    private void hospital7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hospital7MouseEntered

    private void collegesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collegesMouseEntered
        // TODO add your handling code here:
        playSound();

        colleges.setBackground(new Color(52, 53, 55));


    }//GEN-LAST:event_collegesMouseEntered

    private void collegesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collegesMouseExited
        // TODO add your handling code here:
        colleges.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_collegesMouseExited

    private void hospital8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hospital8MouseEntered

    private void universityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityMouseEntered
        // TODO add your handling code here:
        playSound();

        university.setBackground(new Color(52, 53, 55));

    }//GEN-LAST:event_universityMouseEntered

    private void universityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityMouseExited
        // TODO add your handling code here:
        university.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_universityMouseExited

    private void hospital9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hospital9MouseEntered

    private void airportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airportMouseEntered
        // TODO add your handling code here:
        playSound();

        airport.setBackground(new Color(52, 53, 55));

    }//GEN-LAST:event_airportMouseEntered

    private void airportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airportMouseExited
        // TODO add your handling code here:
        airport.setBackground(new Color(32, 33, 35));

    }//GEN-LAST:event_airportMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        mainPage obj = new mainPage();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:

        playSound1();

        hospitalDesign obj = new hospitalDesign();
        obj.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void hotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotelMouseClicked
        // TODO add your handling code here:
        playSound1();
        hotelDesign obj = new hotelDesign();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_hotelMouseClicked

    private void shoppingMallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoppingMallMouseClicked
        // TODO add your handling code here:
        playSound1();
        mallDesign obj = new mallDesign();
        obj.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_shoppingMallMouseClicked

    private void banksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banksMouseClicked
        // TODO add your handling code here:
        playSound1();
        banksDesign obj = new banksDesign();
        obj.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_banksMouseClicked

    private void numbersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numbersMouseClicked
        // TODO add your handling code here:
        playSound1();
        nosDesign obj = new nosDesign();
        obj.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_numbersMouseClicked

    private void restaurantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantsMouseClicked
        // TODO add your handling code here:
        playSound1();
        
        restDesign obj = new restDesign();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_restaurantsMouseClicked

    private void schoolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolsMouseClicked
        // TODO add your handling code here:
        playSound1();

        schoolDesign obj = new schoolDesign();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_schoolsMouseClicked

    private void collegesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collegesMouseClicked
        // TODO add your handling code here:
        playSound1();
        collegeDesign obj = new collegeDesign();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_collegesMouseClicked

    private void hospital8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital8MouseClicked
        // TODO add your handling code here:
        playSound1();

    }//GEN-LAST:event_hospital8MouseClicked

    private void airportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airportMouseClicked
        // TODO add your handling code here:
        playSound1();
        airportDesign obj = new airportDesign();
        obj.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_airportMouseClicked

    private void universityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityMouseClicked
        // TODO add your handling code here:
        playSound1();
        universityDesign obj = new universityDesign();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_universityMouseClicked

    private void hospital6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospital6MouseClicked
        // TODO add your handling code here:
        playSound1();
        restDesign obj = new restDesign();
        obj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_hospital6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subMain111.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subMain111.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subMain111.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subMain111.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subMain111().setVisible(true);
            }
        });
    }

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
//            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
//            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint border

            graphics.setColor(getBackground());
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height);//paint background
            graphics.setColor(getForeground());
            graphics.drawRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height);//paint border

        }
    }

//    public RoundedPanelExample() {
//        setDefaultCloseOperation(EXIT_ON_CLOSE);
//        setTitle("Rounded Panel Example");
//        setResizable(true);
//        setDefaultLookAndFeelDecorated(true);
//        setSize(500, 500);
//
//        Container pane = getContentPane();
//        pane.setLayout(null);
//        pane.setBackground(Color.LIGHT_GRAY);
//
//        JPanel p1 = new RoundedPanel(10, Color.CYAN);
//        p1.setBounds(10, 10, 100, 60);
//        p1.setOpaque(false);
//        pane.add(p1);
//
//        JPanel p2 = new RoundedPanel(15, Color.RED);
//        p2.setBounds(150, 10, 50, 50);
//        p2.setOpaque(false);
//        pane.add(p2);
//
//        JPanel p3 = new RoundedPanel(30);
//        p3.setBounds(230, 10, 100, 150);
//        p3.setOpaque(false);
//        pane.add(p3);
//
//        JPanel p4 = new RoundedPanel(20);
//        p4.setBounds(10, 200, 100, 100);
//        p4.setBackground(Color.GREEN);
//        p4.setOpaque(false);
//        pane.add(p4);
//
//        JPanel p5 = new RoundedPanel(200);
//        p5.setBounds(150, 200, 200, 200);
//        p5.setBackground(Color.BLUE);
//        p5.setOpaque(false);
//        pane.add(p5);
//    }
//
//    public static void main(String[] args) {
//        RoundedPanelExample gui = new RoundedPanelExample();
//        gui.setVisible(true);
//    }
//
//    class RoundedPanel extends JPanel {
//
//        private Color backgroundColor;
//        private int cornerRadius = 15;
//
//        public RoundedPanel(LayoutManager layout, int radius) {
//            super(layout);
//            cornerRadius = radius;
//        }
//
//        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
//            super(layout);
//            cornerRadius = radius;
//            backgroundColor = bgColor;
//        }
//
//        public RoundedPanel(int radius) {
//            super();
//            cornerRadius = radius;
//        }
//
//        public RoundedPanel(int radius, Color bgColor) {
//            super();
//            cornerRadius = radius;
//            backgroundColor = bgColor;
//        }
//
//        @Override
//        protected void paintComponent(Graphics g) {
//            super.paintComponent(g);
//            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
//            int width = getWidth();
//            int height = getHeight();
//            Graphics2D graphics = (Graphics2D) g;
//            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//
//            //Draws the rounded panel with borders.
//            if (backgroundColor != null) {
//                graphics.setColor(backgroundColor);
//            } else {
//                graphics.setColor(getBackground());
//            }
//            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
//            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint border
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JPanel airport;
    private javax.swing.JPanel banks;
    private javax.swing.JButton btn_close;
    private javax.swing.JPanel colleges;
    private javax.swing.JLabel hospital;
    private javax.swing.JLabel hospital1;
    private javax.swing.JLabel hospital2;
    private javax.swing.JLabel hospital3;
    private javax.swing.JLabel hospital4;
    private javax.swing.JLabel hospital5;
    private javax.swing.JLabel hospital6;
    private javax.swing.JLabel hospital7;
    private javax.swing.JLabel hospital8;
    private javax.swing.JLabel hospital9;
    private javax.swing.JPanel hotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel numbers;
    private javax.swing.JPanel panel_drag2;
    private javax.swing.JPanel restaurants;
    private javax.swing.JPanel schools;
    private javax.swing.JPanel shoppingMall;
    private javax.swing.JPanel university;
    // End of variables declaration//GEN-END:variables
}
